name: Test build prestashop flashlight
on: workflow_dispatch

jobs:
  mode-debug-module:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: List content
        run: |
          pwd
          ls -ltr

      - name: Auth Docker GCP
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        # uses: ./.github/actions/auth-docker-gcp
        # with:
        #   docker-password: ${{ secrets.DOCKER_PASSWORD }}
        #   docker-username: ${{ secrets.DOCKER_USERNAME }}


      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and run Docker Compose services
        run: |
          docker-compose up -d
        working-directory: module-test

      - name: Wait for PrestaShop to be ready
        run: |
          while true; do
            HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000)
            echo $HTTP_STATUS
            if [ "$HTTP_STATUS" -eq 200 ]; then
              echo "PrestaShop is ready."
              break
            fi
            sleep 5
          done 2>&1

      - name: Download home page
        run: |
          curl -s http://localhost:8000 > homepage.html
          echo "Contenu de la page" > homepage.html

      - name: List content
        run: |
          pwd
          ls -ltr

