name: Test build prestashop flashlight
on: workflow_dispatch

jobs:
  mode-debug-module:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: List content
        run: |
          pwd
          ls -ltr

      - name: Auth Docker GCP
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        # uses: ./.github/actions/auth-docker-gcp
        # with:
        #   docker-password: ${{ secrets.DOCKER_PASSWORD }}
        #   docker-username: ${{ secrets.DOCKER_USERNAME }}

      - name: Install docker compose
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./module-test/docker-compose.yml"


      - name: Download home page
        run: |
          curl -s http://localhost:8000 > homepage.html
          echo "Contenu de la page" > homepage.html

      - name: List content
        run: |
          pwd
          ls -ltr

